[package]
name = "glicol_parser"
version = "0.12.8"
edition = "2021"
keywords = [
	"audio",
    "music",
	"DSP",
	"synth",
    "synthesizer"
]

license-file = "LICENSE"
description = "Parser for Glicol language."
repository = "https://github.com/chaosprint/glicol.git"
authors = ["Qichao Lan <chaosprint@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
glicol_macros = { path="../macros", version = "0.12.8"}
glicol_synth = { path="../synth", version = "0.12.8"}
hashbrown = "0.12"